# GitHub Pages Configuration

# Site settings
title: "Zach Wan's Portfolio"
description: "A coding portfolio hosted on GitHub Pages"
author: "Zach Wan"

# Theme (choose one from GitHub-supported themes)
theme: jekyll-theme-cayman  # or jekyll-theme-minimal, jekyll-theme-modernist, etc.

# URL settings
baseurl: "" # If hosted under a subpath, specify like "/my-repo"
url: "https://zacharydoodaday.github.io/portfolio"

# Build settings
markdown: kramdown

# Plugins (GitHub Pages supports these by default)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (for themes supporting it)
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/

# Exclude unnecessary files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
